/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/shared/components/App.vue')['default']
    AppCard: typeof import('./src/shared/components/store/AppCard.vue')['default']
    AppDetailModal: typeof import('./src/shared/components/store/AppDetailModal.vue')['default']
    AppError: typeof import('./src/shared/components/feedback/AppError.vue')['default']
    Bg: typeof import('./src/shared/components/base/Bg.vue')['default']
    ConfigManager: typeof import('./src/shared/components/apps/ConfigManager.vue')['default']
    ContextMenu: typeof import('./src/shared/components/layout/ContextMenu.vue')['default']
    DateTimeWidget: typeof import('./src/shared/components/layout/widgets/DateTimeWidget.vue')['default']
    DesktopAppIcon: typeof import('./src/shared/components/layout/widgets/DesktopAppIcon.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    InstalledAppCard: typeof import('./src/shared/components/store/InstalledAppCard.vue')['default']
    InstallProgressModal: typeof import('./src/shared/components/store/InstallProgressModal.vue')['default']
    LanguageSwitcher: typeof import('./src/shared/components/business/LanguageSwitcher.vue')['default']
    Loading: typeof import('./src/shared/components/feedback/Loading.vue')['default']
    Login: typeof import('./src/shared/components/Login.vue')['default']
    Notification: typeof import('./src/shared/components/feedback/Notification.vue')['default']
    NotificationWidget: typeof import('./src/shared/components/layout/widgets/NotificationWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskbarAppIcon: typeof import('./src/shared/components/layout/widgets/TaskbarAppIcon.vue')['default']
    VolumeControl: typeof import('./src/shared/components/layout/widgets/VolumeControl.vue')['default']
    Widget: typeof import('./src/shared/components/base/Widget.vue')['default']
  }
}
