import type { AppConfig } from '@/types/app'
import web from '@/apps/builtIn/utilities/web.vue'
import unresize from '@/apps/builtIn/utilities/unresize.vue'
import unclose from '@/apps/builtIn/utilities/unclose.vue'
import multitask from '@/apps/builtIn/utilities/multitask.vue'
import hidedesktop from '@/apps/builtIn/utilities/hidedesktop.vue'
import EventSystemExample from '@/apps/builtIn/utilities/EventSystemExample.vue'
import dock from '@/apps/builtIn/utilities/dock.vue'
import colorfull from '@/apps/builtIn/utilities/colorfull.vue'
import camera from '@/apps/builtIn/utilities/camera.vue'
import task from '@/apps/builtIn/system/task.vue'
import store from '@/apps/builtIn/system/store.vue'
import setting from '@/apps/builtIn/system/setting.vue'
import finder from '@/apps/builtIn/system/finder.vue'
import ComposablesTest from '@/apps/builtIn/system/ComposablesTest.vue'
import about from '@/apps/builtIn/system/about.vue'
import MyTestApp from '@/apps/custom/MyTestApp.vue'
import AppRegistryDebug from '@/apps/custom/AppRegistryDebug.vue'

/**
 * 自定义应用配置
 * 此文件由 auto-generate-apps 插件自动生成，请勿手动修改
 * 扫描目录: src/apps/builtIn, src/apps/custom, src/apps/3thparty
 * 要添加新应用，请在指定目录下创建 Vue 文件并导出 appConfig
 */
export const systemApps: AppConfig[] = [
  {
    key: 'e300626af7706bca9a3ca355908ecdc7',
    title: 'Web应用',
    icon: 'icon-chrome',
    iconColor: '#fff',
    iconBgColor: '#4285F4',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'utilities',
    description: '用于显示网页内容的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    permissions: [],
    component: web
  },
  {
    key: 'c3adfc81dbc5cf262666bdddc091d525',
    title: '固定尺寸应用',
    icon: 'icon-smallscreen_fill',
    iconColor: '#fff',
    iconBgColor: '#1573fa',
    width: 600,
    height: 400,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'utilities',
    description: '演示固定窗口尺寸功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: unresize
  },
  {
    key: 'c5589533cfcd02af4b1ac6a92a1efdad',
    title: '无法彻底关闭',
    icon: 'icon-wechat-fill',
    iconColor: '#fff',
    iconBgColor: '#24dc72',
    width: 610,
    height: 430,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideWhenClose: true,
    category: 'utilities',
    description: '演示关闭时隐藏而非退出的功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: unclose
  },
  {
    key: 'e0609d06eac32e9e6014595d0814cb48',
    title: '多任务应用',
    icon: 'icon-multitask',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 500,
    height: 300,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    multiTask: true,
    keepInDock: false,
    category: 'utilities',
    description: '演示多任务功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: multitask
  },
  {
    key: '3e4431cb51f37d4a195f4a68aae2916d',
    title: '不在桌面显示',
    icon: 'icon-shezhi',
    iconColor: '#333',
    iconBgColor: '#d4dbef',
    width: 500,
    height: 300,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: true,
    keepInDock: true,
    category: 'utilities',
    description: '演示仅在 Dock 显示的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: hidedesktop
  },
  {
    key: '058e255307e1bf6789a79b25a3436af0',
    title: 'ES',
    icon: 'icon-MIS_bangongOA',
    iconColor: '#fff',
    iconBgColor: '#022732',
    width: 420,
    height: 350,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'utilities',
    description: '演示常驻 Dock 功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: EventSystemExample
  },
  {
    key: 'c9f53f1c94bb95e1a14ca86c58a39be9',
    title: '常驻 Dock 应用',
    icon: 'icon-MIS_bangongOA',
    iconColor: '#fff',
    iconBgColor: '#022732',
    width: 420,
    height: 350,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'utilities',
    description: '演示常驻 Dock 功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: dock
  },
  {
    key: 'f74d2210e6bdb5847676e04933c34290',
    title: '花里胡哨',
    icon: 'icon-loading',
    iconColor: '#fff',
    iconBgColor: '#ff4500',
    width: 420,
    height: 310,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'entertainment',
    description: '演示自定义窗口样式功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: colorfull
  },
  {
    key: 'fc647623586b47ea92f7cfc2ac779d70',
    title: 'Photo Booth',
    icon: 'icon-camera1',
    iconColor: '#fff',
    iconBgColor: '#E24637',
    width: 540,
    height: 540,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'graphics',
    description: '相机拍照应用演示',
    version: '1.0.0',
    author: 'Demo Team',
    demo: true,
    featured: false,
    component: camera
  },
  {
    key: 'd0d240d5e08c3b10d4f91eae8defd75e',
    title: 'Activity Monitor',
    icon: '📊',
    iconColor: '#fff',
    iconBgColor: '#34C759',
    width: 600,
    height: 400,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    category: 'system',
    description: '活动监视器',
    version: '1.0.0',
    author: 'System',
    tags: [],
    system: true,
    essential: false,
    singleton: true,
    component: task
  },
  {
    key: '90d8b684cc376d4175adde070c6096d3',
    title: 'App Store',
    icon: '🛍️',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 1000,
    height: 700,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'system',
    description: '应用商店',
    version: '1.0.0',
    author: 'System',
    tags: [],
    permissions: [],
    system: true,
    essential: false,
    singleton: true,
    component: store
  },
  {
    key: 'cc02cf00ad37023d5eda3b05bbdb113e',
    title: 'System Preferences',
    icon: '⚙️',
    iconColor: '#fff',
    iconBgColor: '#8E8E93',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    keepInDock: true,
    category: 'system',
    description: '系统偏好设置',
    version: '1.0.0',
    author: 'System',
    tags: [],
    system: true,
    essential: true,
    singleton: true,
    component: setting
  },
  {
    key: '52849bcf065bb72646127e5a1e22a018',
    title: 'Finder',
    icon: '📁',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    keepInDock: true,
    category: 'system',
    description: '文件管理器',
    version: '1.0.0',
    author: 'System',
    tags: [],
    system: true,
    essential: true,
    singleton: true,
    component: finder
  },
  {
    key: 'b8c0666ed3be27c90b4e9aa7590152d7',
    title: 'Composables Test',
    icon: '🧪',
    iconColor: '#fff',
    iconBgColor: '#4CAF50',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    category: 'development',
    description: '测试和演示组合式函数功能',
    version: '1.0.0',
    author: 'Developer',
    tags: [],
    system: true,
    essential: false,
    singleton: false,
    component: ComposablesTest
  },
  {
    key: '29cab3126f21472bf8f990d57ff54ab0',
    title: '关于本机',
    icon: 'icon-about',
    iconColor: '#fff',
    iconBgColor: '#23282d',
    width: 400,
    height: 250,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: true,
    category: 'system',
    description: '显示系统信息和版本详情',
    version: '1.0.0',
    author: 'System',
    system: true,
    essential: false,
    singleton: true,
    component: about
  },
  {
    key: 'ff6a6a3d0160268a50b9abc347ba2145',
    title: '我的测试应用',
    icon: 'icon-loading',
    iconColor: '#667eea',
    iconBgColor: 'rgba(102, 126, 234, 0.1)',
    width: 900,
    height: 700,
    minWidth: 320,
    minHeight: 240,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    alwaysOnTop: false,
    modal: false,
    transparent: false,
    frame: true,
    titleBarStyle: 'default',
    backgroundColor: '#ffffff',
    opacity: 1,
    shadow: true,
    animation: true,
    keepInDock: true,
    hideInDesktop: false,
    hideWhenClose: false,
    autoFocus: true,
    category: 'custom',
    tags: [],
    version: '1.0.0',
    author: '动态加载系统',
    description: '这是一个用于测试动态加载功能的示例应用',
    permissions: [],
    dependencies: [],
    component: MyTestApp
  },
  {
    key: '45fb1d8f12e67974a1ad991c3d3d0131',
    title: '应用注册表调试',
    icon: 'icon-bug',
    iconBgColor: '#FF6B6B',
    iconColor: '#FFFFFF',
    category: 'development',
    tags: [],
    version: '1.0.0',
    description: '用于调试应用注册表状态的工具',
    component: AppRegistryDebug
  }
]
