import type { AppConfig } from '@/types/app'
import { simpleApps } from './simple-apps'
import custom__MyTestApp from '@/apps/custom/MyTestApp/index.vue'
import custom__AppRegistryDebug from '@/apps/custom/AppRegistryDebug/index.vue'
import builtIn_utilities_web from '@/apps/builtIn/utilities/web/index.vue'
import builtIn_utilities_unresize from '@/apps/builtIn/utilities/unresize/index.vue'
import builtIn_utilities_unclose from '@/apps/builtIn/utilities/unclose/index.vue'
import builtIn_utilities_multitask from '@/apps/builtIn/utilities/multitask/index.vue'
import builtIn_utilities_hidedesktop from '@/apps/builtIn/utilities/hidedesktop/index.vue'
import builtIn_utilities_EventSystemExample from '@/apps/builtIn/utilities/EventSystemExample/index.vue'
import builtIn_utilities_dock from '@/apps/builtIn/utilities/dock/index.vue'
import builtIn_utilities_colorfull from '@/apps/builtIn/utilities/colorfull/index.vue'
import builtIn_utilities_camera from '@/apps/builtIn/utilities/camera/index.vue'
import builtIn_system_task from '@/apps/builtIn/system/task/index.vue'
import builtIn_system_store from '@/apps/builtIn/system/store/index.vue'
import builtIn_system_setting from '@/apps/builtIn/system/setting/index.vue'
import builtIn_system_finder from '@/apps/builtIn/system/finder/index.vue'
import builtIn_system_composablesTest from '@/apps/builtIn/system/composablesTest/index.vue'
import builtIn_system_about from '@/apps/builtIn/system/about/index.vue'

/**
 * 应用键值常量
 * 此文件由 auto-generate-apps 插件自动生成，请勿手动修改
 * 扫描目录: src/apps/
 */
export const APP_KEYS = {
  APPKEY_CUSTOM__MYTESTAPP: 'custom__mytestapp',
  APPKEY_CUSTOM__APPREGISTRYDEBUG: 'custom__appregistrydebug',
  APPKEY_BUILTIN_UTILITIES_WEB: 'builtin_utilities_web',
  APPKEY_BUILTIN_UTILITIES_UNRESIZE: 'builtin_utilities_unresize',
  APPKEY_BUILTIN_UTILITIES_UNCLOSE: 'builtin_utilities_unclose',
  APPKEY_BUILTIN_UTILITIES_MULTITASK: 'builtin_utilities_multitask',
  APPKEY_BUILTIN_UTILITIES_HIDEDESKTOP: 'builtin_utilities_hidedesktop',
  APPKEY_BUILTIN_UTILITIES_EVENTSYSTEMEXAMPLE: 'builtin_utilities_eventsystemexample',
  APPKEY_BUILTIN_UTILITIES_DOCK: 'builtin_utilities_dock',
  APPKEY_BUILTIN_UTILITIES_COLORFULL: 'builtin_utilities_colorfull',
  APPKEY_BUILTIN_UTILITIES_CAMERA: 'builtin_utilities_camera',
  APPKEY_BUILTIN_SYSTEM_TASK: 'builtin_system_task',
  APPKEY_BUILTIN_SYSTEM_STORE: 'builtin_system_store',
  APPKEY_BUILTIN_SYSTEM_SETTING: 'builtin_system_setting',
  APPKEY_BUILTIN_SYSTEM_FINDER: 'builtin_system_finder',
  APPKEY_BUILTIN_SYSTEM_COMPOSABLESTEST: 'builtin_system_composablestest',
  APPKEY_BUILTIN_SYSTEM_ABOUT: 'builtin_system_about'
} as const

export type AppKey = typeof APP_KEYS[keyof typeof APP_KEYS]

/**
 * 动态扫描的应用配置
 * 此文件由 auto-generate-apps 插件自动生成，请勿手动修改
 * 扫描目录: src/apps/
 * 要添加新应用，请在指定目录下创建 Vue 文件并导出 appConfig
 */
export const scanApps: AppConfig[] = [
  {
    key: 'custom__mytestapp',
    title: '我的测试应用',
    icon: 'icon-loading',
    iconColor: '#667eea',
    iconBgColor: 'rgba(102, 126, 234, 0.1)',
    width: 900,
    height: 700,
    minWidth: 320,
    minHeight: 240,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    alwaysOnTop: false,
    modal: false,
    transparent: false,
    frame: true,
    titleBarStyle: 'default',
    backgroundColor: '#ffffff',
    opacity: 1,
    shadow: true,
    animation: true,
    keepInDock: true,
    hideInDesktop: false,
    hideWhenClose: false,
    autoFocus: true,
    category: 'custom',
    tags: [],
    version: '1.0.0',
    author: '动态加载系统',
    description: '这是一个用于测试动态加载功能的示例应用',
    permissions: ["storage"],
    dependencies: [],
    _id: 'ff6a6a3d0160268a50b9abc347ba2145',
    group: '',
    component: custom__MyTestApp
  },
  {
    key: 'custom__appregistrydebug',
    title: '应用注册表调试',
    icon: 'icon-bug',
    iconBgColor: '#FF6B6B',
    iconColor: '#FFFFFF',
    category: 'custom',
    tags: ["debug","registry","development"],
    version: '1.0.0',
    description: '用于调试应用注册表状态的工具',
    width: 600,
    height: 700,
    _id: '45fb1d8f12e67974a1ad991c3d3d0131',
    group: '',
    component: custom__AppRegistryDebug
  },
  {
    key: 'builtin_utilities_web',
    title: 'Web应用',
    icon: 'icon-chrome',
    iconColor: '#fff',
    iconBgColor: '#4285F4',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'builtIn',
    description: '用于显示网页内容的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: ["web","iframe"],
    demo: true,
    featured: false,
    permissions: ["network"],
    _id: 'e300626af7706bca9a3ca355908ecdc7',
    group: 'utilities',
    component: builtIn_utilities_web
  },
  {
    key: 'builtin_utilities_unresize',
    title: '固定尺寸应用',
    icon: 'icon-smallscreen_fill',
    iconColor: '#fff',
    iconBgColor: '#1573fa',
    width: 600,
    height: 400,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'builtIn',
    description: '演示固定窗口尺寸功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: ["window","fixed-size"],
    demo: true,
    featured: false,
    _id: 'c3adfc81dbc5cf262666bdddc091d525',
    group: 'utilities',
    component: builtIn_utilities_unresize
  },
  {
    key: 'builtin_utilities_unclose',
    title: '无法彻底关闭',
    icon: 'icon-wechat-fill',
    iconColor: '#fff',
    iconBgColor: '#24dc72',
    width: 610,
    height: 430,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideWhenClose: true,
    category: 'builtIn',
    description: '演示关闭时隐藏而非退出的功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: ["window","hide-on-close"],
    demo: true,
    featured: false,
    _id: 'c5589533cfcd02af4b1ac6a92a1efdad',
    group: 'utilities',
    component: builtIn_utilities_unclose
  },
  {
    key: 'builtin_utilities_multitask',
    title: '多任务应用',
    icon: 'icon-multitask',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 500,
    height: 300,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    multiTask: true,
    keepInDock: false,
    category: 'builtIn',
    description: '演示多任务功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: ["multitask","demo"],
    demo: true,
    featured: false,
    _id: 'e0609d06eac32e9e6014595d0814cb48',
    group: 'utilities',
    component: builtIn_utilities_multitask
  },
  {
    key: 'builtin_utilities_hidedesktop',
    title: '不在桌面显示',
    icon: 'icon-shezhi',
    iconColor: '#333',
    iconBgColor: '#d4dbef',
    width: 500,
    height: 300,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: true,
    keepInDock: true,
    category: 'builtIn',
    description: '演示仅在 Dock 显示的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: ["dock-only","hidden"],
    demo: true,
    featured: false,
    _id: '3e4431cb51f37d4a195f4a68aae2916d',
    group: 'utilities',
    component: builtIn_utilities_hidedesktop
  },
  {
    key: 'builtin_utilities_eventsystemexample',
    title: 'ES',
    icon: 'icon-MIS_bangongOA',
    iconColor: '#fff',
    iconBgColor: '#022732',
    width: 420,
    height: 350,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'builtIn',
    description: '演示常驻 Dock 功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: ["dock","persistent"],
    demo: true,
    featured: false,
    _id: '058e255307e1bf6789a79b25a3436af0',
    group: 'utilities',
    component: builtIn_utilities_EventSystemExample
  },
  {
    key: 'builtin_utilities_dock',
    title: '常驻 Dock 应用',
    icon: 'icon-MIS_bangongOA',
    iconColor: '#fff',
    iconBgColor: '#022732',
    width: 420,
    height: 350,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'builtIn',
    description: '演示常驻 Dock 功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: ["dock","persistent"],
    demo: true,
    featured: false,
    _id: 'c9f53f1c94bb95e1a14ca86c58a39be9',
    group: 'utilities',
    component: builtIn_utilities_dock
  },
  {
    key: 'builtin_utilities_colorfull',
    title: '花里胡哨',
    icon: 'icon-loading',
    iconColor: '#fff',
    iconBgColor: '#ff4500',
    width: 420,
    height: 310,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'builtIn',
    description: '演示自定义窗口样式功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: ["colorful","custom-style"],
    demo: true,
    featured: false,
    _id: 'f74d2210e6bdb5847676e04933c34290',
    group: 'utilities',
    component: builtIn_utilities_colorfull
  },
  {
    key: 'builtin_utilities_camera',
    title: 'Photo Booth',
    icon: 'icon-camera1',
    iconColor: '#fff',
    iconBgColor: '#E24637',
    width: 540,
    height: 540,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'builtIn',
    description: '相机拍照应用演示',
    version: '1.0.0',
    author: 'Demo Team',
    demo: true,
    featured: false,
    _id: 'fc647623586b47ea92f7cfc2ac779d70',
    group: 'utilities',
    component: builtIn_utilities_camera
  },
  {
    key: 'builtin_system_task',
    title: 'Activity Monitor',
    icon: '📊',
    iconColor: '#fff',
    iconBgColor: '#34C759',
    width: 600,
    height: 400,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    category: 'builtIn',
    description: '活动监视器',
    version: '1.0.0',
    author: 'System',
    tags: ["system","monitor","task"],
    system: true,
    essential: false,
    singleton: true,
    _id: 'd0d240d5e08c3b10d4f91eae8defd75e',
    group: 'system',
    component: builtIn_system_task
  },
  {
    key: 'builtin_system_store',
    title: 'App Store',
    icon: '🛍️',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 1000,
    height: 700,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'builtIn',
    description: '应用商店',
    version: '1.0.0',
    author: 'System',
    tags: ["store","apps","download"],
    permissions: ["network"],
    system: true,
    essential: false,
    singleton: true,
    _id: '90d8b684cc376d4175adde070c6096d3',
    group: 'system',
    component: builtIn_system_store
  },
  {
    key: 'builtin_system_setting',
    title: 'System Preferences',
    icon: '⚙️',
    iconColor: '#fff',
    iconBgColor: '#8E8E93',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    keepInDock: true,
    category: 'builtIn',
    description: '系统偏好设置',
    version: '1.0.0',
    author: 'System',
    tags: ["system","preferences","settings"],
    system: true,
    essential: true,
    singleton: true,
    _id: 'cc02cf00ad37023d5eda3b05bbdb113e',
    group: 'system',
    component: builtIn_system_setting
  },
  {
    key: 'builtin_system_finder',
    title: 'Finder',
    icon: '📁',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    keepInDock: true,
    category: 'builtIn',
    description: '文件管理器',
    version: '1.0.0',
    author: 'System',
    tags: ["file","manager","system"],
    system: true,
    essential: true,
    singleton: true,
    _id: '52849bcf065bb72646127e5a1e22a018',
    group: 'system',
    component: builtIn_system_finder
  },
  {
    key: 'builtin_system_composablestest',
    title: 'Composables Test',
    icon: '🧪',
    iconColor: '#fff',
    iconBgColor: '#4CAF50',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    category: 'builtIn',
    description: '测试和演示组合式函数功能',
    version: '1.0.0',
    author: 'Developer',
    tags: ["test","composables","vue"],
    system: true,
    essential: false,
    singleton: false,
    _id: '3762252243abd5fad49457a4907d0e7b',
    group: 'system',
    component: builtIn_system_composablesTest
  },
  {
    key: 'builtin_system_about',
    title: '关于本机',
    icon: 'icon-about',
    iconColor: '#fff',
    iconBgColor: '#23282d',
    width: 400,
    height: 250,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: true,
    category: 'builtIn',
    description: '显示系统信息和版本详情',
    version: '1.0.0',
    author: 'System',
    system: true,
    essential: false,
    singleton: true,
    _id: '29cab3126f21472bf8f990d57ff54ab0',
    group: 'system',
    component: builtIn_system_about
  }
]

/**
 * 所有应用配置（合并动态扫描和手动配置）
 */
export const Apps: AppConfig[] = [...scanApps, ...simpleApps]
