import type { AppConfig } from '@/types/app'
import demo_web from '@/applications/built-in/utilities/web.vue'
import demo_unresize from '@/applications/built-in/utilities/unresize.vue'
import demo_unclose from '@/applications/built-in/utilities/unclose.vue'
import demo_multitask from '@/applications/built-in/utilities/multitask.vue'
import demo_hidedesktop from '@/applications/built-in/utilities/hidedesktop.vue'
import demo_es from '@/applications/built-in/utilities/EventSystemExample.vue'
import demo_dock from '@/applications/built-in/utilities/dock.vue'
import demo_colorfull from '@/applications/built-in/utilities/colorfull.vue'
import demo_camera from '@/applications/built-in/utilities/camera.vue'
import system_task from '@/applications/built-in/system/task.vue'
import system_store from '@/applications/built-in/system/store.vue'
import system_setting from '@/applications/built-in/system/setting.vue'
import system_finder from '@/applications/built-in/system/finder.vue'
import composables_test from '@/applications/built-in/system/ComposablesTest.vue'
import system_about from '@/applications/built-in/system/about.vue'
import MyTestApp from '@/applications/user-custom/MyTestApp.vue'
import app_registry_debug from '@/applications/user-custom/AppRegistryDebug.vue'

/**
 * 自定义应用配置
 * 此文件由 auto-generate-apps 插件自动生成，请勿手动修改
 * 扫描目录: src/applications/built-in, src/applications/user-custom, src/applications/third-party
 * 要添加新应用，请在指定目录下创建 Vue 文件并导出 appConfig
 */
export const systemApps: AppConfig[] = [
  {
    key: 'demo_web',
    title: 'Web应用',
    icon: 'icon-chrome',
    iconColor: '#fff',
    iconBgColor: '#4285F4',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'utilities',
    description: '用于显示网页内容的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    permissions: [],
    component: demo_web
  },
  {
    key: 'demo_unresize',
    title: '固定尺寸应用',
    icon: 'icon-smallscreen_fill',
    iconColor: '#fff',
    iconBgColor: '#1573fa',
    width: 600,
    height: 400,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'utilities',
    description: '演示固定窗口尺寸功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: demo_unresize
  },
  {
    key: 'demo_unclose',
    title: '无法彻底关闭',
    icon: 'icon-wechat-fill',
    iconColor: '#fff',
    iconBgColor: '#24dc72',
    width: 610,
    height: 430,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideWhenClose: true,
    category: 'utilities',
    description: '演示关闭时隐藏而非退出的功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: demo_unclose
  },
  {
    key: 'demo_multitask',
    title: '多任务应用',
    icon: 'icon-multitask',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 500,
    height: 300,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    multiTask: true,
    keepInDock: false,
    category: 'utilities',
    description: '演示多任务功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: demo_multitask
  },
  {
    key: 'demo_hidedesktop',
    title: '不在桌面显示',
    icon: 'icon-shezhi',
    iconColor: '#333',
    iconBgColor: '#d4dbef',
    width: 500,
    height: 300,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: true,
    keepInDock: true,
    category: 'utilities',
    description: '演示仅在 Dock 显示的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: demo_hidedesktop
  },
  {
    key: 'demo_es',
    title: 'ES',
    icon: 'icon-MIS_bangongOA',
    iconColor: '#fff',
    iconBgColor: '#022732',
    width: 420,
    height: 350,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'utilities',
    description: '演示常驻 Dock 功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: demo_es
  },
  {
    key: 'demo_dock',
    title: '常驻 Dock 应用',
    icon: 'icon-MIS_bangongOA',
    iconColor: '#fff',
    iconBgColor: '#022732',
    width: 420,
    height: 350,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'utilities',
    description: '演示常驻 Dock 功能的应用',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: demo_dock
  },
  {
    key: 'demo_colorfull',
    title: '花里胡哨',
    icon: 'icon-loading',
    iconColor: '#fff',
    iconBgColor: '#ff4500',
    width: 420,
    height: 310,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'entertainment',
    description: '演示自定义窗口样式功能',
    version: '1.0.0',
    author: 'Demo Team',
    tags: [],
    demo: true,
    featured: false,
    component: demo_colorfull
  },
  {
    key: 'demo_camera',
    title: 'Photo Booth',
    icon: 'icon-camera1',
    iconColor: '#fff',
    iconBgColor: '#E24637',
    width: 540,
    height: 540,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    category: 'graphics',
    description: '相机拍照应用演示',
    version: '1.0.0',
    author: 'Demo Team',
    demo: true,
    featured: false,
    component: demo_camera
  },
  {
    key: 'system_task',
    title: 'Activity Monitor',
    icon: '📊',
    iconColor: '#fff',
    iconBgColor: '#34C759',
    width: 600,
    height: 400,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    category: 'system',
    description: '活动监视器',
    version: '1.0.0',
    author: 'System',
    tags: [],
    system: true,
    essential: false,
    singleton: true,
    component: system_task
  },
  {
    key: 'system_store',
    title: 'App Store',
    icon: '🛍️',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 1000,
    height: 700,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    keepInDock: true,
    category: 'system',
    description: '应用商店',
    version: '1.0.0',
    author: 'System',
    tags: [],
    permissions: [],
    system: true,
    essential: false,
    singleton: true,
    component: system_store
  },
  {
    key: 'system_setting',
    title: 'System Preferences',
    icon: '⚙️',
    iconColor: '#fff',
    iconBgColor: '#8E8E93',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    keepInDock: true,
    category: 'system',
    description: '系统偏好设置',
    version: '1.0.0',
    author: 'System',
    tags: [],
    system: true,
    essential: true,
    singleton: true,
    component: system_setting
  },
  {
    key: 'system_finder',
    title: 'Finder',
    icon: '📁',
    iconColor: '#fff',
    iconBgColor: '#007AFF',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    keepInDock: true,
    category: 'system',
    description: '文件管理器',
    version: '1.0.0',
    author: 'System',
    tags: [],
    system: true,
    essential: true,
    singleton: true,
    component: system_finder
  },
  {
    key: 'composables_test',
    title: 'Composables Test',
    icon: '🧪',
    iconColor: '#fff',
    iconBgColor: '#4CAF50',
    width: 800,
    height: 600,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: false,
    category: 'development',
    description: '测试和演示组合式函数功能',
    version: '1.0.0',
    author: 'Developer',
    tags: [],
    system: true,
    essential: false,
    singleton: false,
    component: composables_test
  },
  {
    key: 'system_about',
    title: '关于本机',
    icon: 'icon-about',
    iconColor: '#fff',
    iconBgColor: '#23282d',
    width: 400,
    height: 250,
    resizable: false,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    hideInDesktop: true,
    category: 'system',
    description: '显示系统信息和版本详情',
    version: '1.0.0',
    author: 'System',
    system: true,
    essential: false,
    singleton: true,
    component: system_about
  },
  {
    key: 'MyTestApp',
    title: '我的测试应用',
    icon: 'icon-loading',
    iconColor: '#667eea',
    iconBgColor: 'rgba(102, 126, 234, 0.1)',
    width: 900,
    height: 700,
    minWidth: 320,
    minHeight: 240,
    resizable: true,
    draggable: true,
    closable: true,
    minimizable: true,
    maximizable: true,
    alwaysOnTop: false,
    modal: false,
    transparent: false,
    frame: true,
    titleBarStyle: 'default',
    backgroundColor: '#ffffff',
    opacity: 1,
    shadow: true,
    animation: true,
    keepInDock: true,
    hideInDesktop: false,
    hideWhenClose: false,
    autoFocus: true,
    category: 'custom',
    tags: [],
    version: '1.0.0',
    author: '动态加载系统',
    description: '这是一个用于测试动态加载功能的示例应用',
    permissions: [],
    dependencies: [],
    component: MyTestApp
  },
  {
    key: 'app_registry_debug',
    title: '应用注册表调试',
    icon: 'icon-bug',
    iconBgColor: '#FF6B6B',
    iconColor: '#FFFFFF',
    category: 'development',
    tags: [],
    version: '1.0.0',
    description: '用于调试应用注册表状态的工具',
    component: app_registry_debug
  }
]
